config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    root 'top#index'

    resources :topics do
        resources:comments
        post :confirm, on: :collection
    end

    resources :conversations do
        resources :messages
    end

    devise_for :users, controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks"
    }

    resources :users, only: [:index, :show]
     resources :relationships, only: [:create, :destroy]

if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # コメントを保存、投稿するためのアクションです。
    def create
        # topicをパラメータの値から探し出し,topicに紐づくcommentsとしてbuildします。
        @comment = current_user.comments.build(comment_params)
        @topic = @comment.topic
        @notification = @comment.notifications.build(user_id:@topic.user_id)

        # クライアント要求に応じてフォーマットを変更
        respond_to do |format|
            if @comment.save
                format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
                format.js { render :index }
                unless @comment.topic.user_id==current_user.id
                    Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'comment_created', {
                    message: 'あなたの作成したトピックにコメントが付きました'
                    })
                end
                Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'notification_created', {
                unread_counts: Notification.where(user_id: @comment.topic.user.id, read: false).count
                })
            else
                format.html { render :new }
            end
        end
    end

    def update
        @comment = Comment.find(params[:id])
        if @comment.update(comment_params)
            redirect_to topic_path(@comment.topic.id), notice: 'コメントが修正されました'
        else
            render 'edit'
        end
    end


    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy

        respond_to do |format|
            format.html { redirect_to topic_path(@topic), notice: 'コメントを削除しました。' }
            format.js { render :index }
        end
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    private
    # ストロングパラメーター
    def comment_params
        params.require(:comment).permit(:topic_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment],remote:true) do |f| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
                <h2><%= comment.errors.count %>件のエラーがあります。</h2>

                <ul>
                    <% comment.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
        </div>
    <% end %>
    <%= f.hidden_field :topic_id %>
    <div class="field">
        <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
    <% comments.each do |comment| %>
        <% unless comment.id.nil? %>
            <li>
                <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
                <p class="left"><%= comment.content %></p>
                <% if current_user.id == comment.user.id %>
                    <p class="right">
                        <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
                        <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
                    </p>
                <% end %>
            </li>
        <% end %>
    <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>コメントを編集する</h2>
    <p id="notice"><%= notice %></p>
    <!-- 変数を持ってくる、パスを入れる -->
    <!-- editの場合は自動的にupdateアクションへ渡るようになる -->
    <%= form_for(@comment, url:topic_comment_path) do |f| %>
      <%= f.label :content %>
      <%= f.text_field :content, class:'form-control' %>
      <br>
      <%= f.submit '編集する', class: 'btn btn-primary btn-block' %>
    <% end %>


    <%= link_to "コメント一覧画面にもどる", topic_path(@comment.topic.id) %>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')