config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    root 'top#index'

    resources :topics do
        resources:comments
        post :confirm, on: :collection
    end

    resources :conversations do
        resources :messages
    end

    devise_for :users, controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks"
    }

    resources :users, only: [:index, :show]
     resources :relationships, only: [:create, :destroy]

if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    validates:title,presence:true
    belongs_to :user
    has_many :comments, dependent: :destroy

    mount_uploader :pictures, AvatarUploader

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

    before_action :authenticate_user!

    before_action :set_topic, only: [:show, :edit, :update, :destroy]

    def index
        @topics = Topic.all
        respond_to do |format|
            format.html
            format.js
        end
    end




    # showアククションを定義します。入力フォームと一覧を表示するためインスタンスを2つ生成します。
    def show
      @comment = @topic.comments.build
      @comments = @topic.comments
      Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
    end

    def new
        if params[:back]
            @topic = Topic.new(topics_params)
        else
            @topic = Topic.new
        end
    end

    def create

        @topic = Topic.new(topics_params)
        @topic.user_id = current_user.id

        if @topic.save
            redirect_to topics_path, notice: "トピックを作成しました!"
            NoticeMailer.sendmail_topic(@topic).deliver
        else
           render 'new'
        end
    end

    def edit
    end

    def update
        @topic.update(topics_params)
        if @topic.save
            redirect_to topics_path
        else render 'edit'
        end
    end

    def destroy
        @topic.destroy
        redirect_to topics_path
    end

    def confirm
        @topic = Topic.new(topics_params)
        render :new if @topic.invalid?
    end

    private
        def topics_params
            params.require(:topic).permit(:title, :content, :pictures, :pictures_cache)
        end

    def set_topic
        @topic = Topic.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_topics_path
        elsif action_name == 'edit'
            topic_path
        end
    end
end

app/views/topics/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@topic,url:choose_new_or_edit) do |f| %>
    <% if @topic.errors.any? %>
        <div id="error_explanation">

            <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

            <ul>
                <% @topic.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :タイトル %>
    <%= f.text_field :title, class: 'form-control' %>
    <br>
    <%= f.label :内容 %>
    <%= f.text_field :content, class: 'form-control' %>
    <br>
    <div class="field">
      <%= f.label :アップロード画像 %>
      <%= f.file_field :pictures %>
      <%= f.hidden_field :pictures_cache %>
   </div>
    <br>
    <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "トピック一覧画面にもどる", topics_path %>

app/views/topics/confirm.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h3>以下の内容で、送信する。</h3>

        <%= form_for(@topic) do |f| %>
            <%= f.hidden_field :title %>
            <%= f.hidden_field :content %>

            <p>タイトル:<%= @topic.title %></p>
            <p>本文:<%= @topic.content %></p>

            <div class="field">
              <!-- <%= image_tag(@topic.pictures) %> -->
              <%= f.hidden_field :pictures_cache %>
              <%= hidden_field_tag :"cache[pictures]", @topic.pictures.cache_name %>

           </div>

            <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
        <% end %>

        <%= form_for(@topic, url: new_topic_path, method:'get') do |f| %>
            <%= f.hidden_field :title %>
            <%= f.hidden_field :content %>

             <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
        <% end %>
    </div>
</div>

app/views/topics/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>トピックを編集する</h2>
        <%= render 'form' %>
    </div>
</div>

app/views/topics/index.html.erb
<div class="container">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">

        <%= notice %>
        <h1>トピック一覧</h1>
        <%= link_to "トピックを作成する", new_topic_path, class: 'btn btn-default' %>

        <% @topics.each do |topic| %>
            <div class="row">
                <%= profile_img(topic.user) %>
                <%= topic.user.name %>
                <%= link_to topic_path(topic) do %>
                    <h4><strong><%= topic.title %></strong></h4>
                <% end %>
                <div class= ".pic">
                <%= image_tag(topic.pictures) %>
                </div>
                <p>本文:<%= topic.content %></p>
                <%= link_to "トピックを編集する", edit_topic_path(topic.id), class: 'btn btn-default btn-sm btn-success' %>
                <%= link_to "トピックを削除する", topic_path(topic.id), method: :delete, data:{confirm:'本当に削除していいですか'}, class: 'btn btn-default btn-sm btn btn-danger' %>
                <br>
            </div>
        <% end %>
        <br>


    </div>
</div>

app/views/topics/new.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>トピックを作成する</h2>
        <%= render 'form' %>
    </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="topic-text">
      <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @topic.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @topic.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <% if current_user.id == @topic.user_id %>
      <%= link_to '編集', edit_topic_path(@topic) %> |
    <% end %>
    <%= link_to '戻る', topics_path %>
  </div>
</div>