config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    root 'top#index'

    resources :topics do
        resources:comments
        post :confirm, on: :collection
    end

    resources :conversations do
        resources :messages
    end

    devise_for :users, controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks"
    }

    resources :users, only: [:index, :show]
     resources :relationships, only: [:create, :destroy]

if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
before_action :authenticate_user!
    def index
        @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/views/notifications/index.html.erb
<h2>お知らせ</h2>
<ul>
  <% @notifications.each do |notification| %>
  <hr>
    <li>
      <span><%= notification.read %></span>
      <p>
          <%= notification.comment.user.try(:name) %>さんが
              あなたのブログ（<%= link_to "#{notification.comment.topic.title}", topic_path(notification.comment.topic, notification_id: notification.id) %>）にコメントしました。
      </p>
      <p><%= notification.created_at %></p>
    </li>
  <% end %>
</ul>