config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    root 'top#index'

    resources :topics do
        resources:comments
        post :confirm, on: :collection
    end

    resources :conversations do
        resources :messages
    end

    devise_for :users, controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks"
    }

    resources :users, only: [:index, :show]
     resources :relationships, only: [:create, :destroy]

if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
            <title>Racebook</title>
            <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
            <%= csrf_meta_tags %>
            <% if user_signed_in? %>
                <script>
                    var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
                        cluster: 'ap1',
                        encrypted: true
                    });

                    var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
                    channel.bind('comment_created', function(data) {
                    alert(data.message);
                    });
                    channel.bind('notification_created', function(data) {
                    $('#unread_count').html(data.unread_counts);
                    });
                </script>
            <% end %>
    </head>


<header>
    <ul>
        <li><%= link_to "Racebook", root_path %></li>

        <% if user_signed_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>


                <ul class="dropdown-menu">
                    <li><%= link_to "TOPIC", topics_path %></li>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                    <li><%= link_to 'マイページ', edit_user_registration_path %></li>
                    <li><%= link_to 'ユーザー一覧', users_path %></li>
                    <li><%= link_to "メッセージ", conversations_path %></li>
                </ul>

        </li>
        <% end %>


        <div class="align-right">
            <% if user_signed_in? %>

                <li>
                    <%= link_to notifications_index_path do %>
                        <i class="fa fa-bell fa-1x"><span id="unread_count"><%= @notifications_count %></span></i>
                    <% end %>
                </li>
            <% else %>
            <% end %>
        </div>

    </ul>
</header>

    <%= yield %>

    <footer>
        <p>大課題３</p>
        <p>© 2015-2016 Copyright 菅沼　格</p>
    </footer>